[package]
name = "future_prj"
version = "0.1.0"
authors = ["hongyuanyang <hongyuanyang@huobi.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
futures03 = { package = "futures-preview", version = "=0.3.0-alpha.17", features = ["compat"] }
tokio-core="*"
tokio = "0.1.22"
chrono = "0.4.6"
